"""
SLAYBILL — emit firms_index.json from shows.json marketing_firms entries.

Day 1 scope: read shows.json, normalize each show's marketing_firms array,
emit web/data/firms_index.json (firm -> list of shows). build_live_shows.py
already passes marketing_firms through to shows_live.json so the homepage
can render chips inline; this builder produces the firm-pivoted view that
the future /firms.html page (Pro) will consume.

Validation rules:
  - At most one is_primary=true per show. If multiple are flagged, the first
    wins and the rest are demoted with a warning printed to stderr.
  - role must be in the locked taxonomy. Unknown roles are dropped with
    a warning so a typo doesn't render a broken chip.

Run:
    uv run python builders/build_firms.py
"""

import json
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROJECT_ROOT = HERE.parent
SHOWS_JSON = PROJECT_ROOT / "data" / "shows.json"
OUT_PATH = PROJECT_ROOT / "web" / "data" / "firms_index.json"

VALID_ROLES = {
    "lead_agency", "press", "digital", "creative",
    "oo_h", "social", "pr", "media_buy",
}

ROLE_DISPLAY = {
    "lead_agency": "Lead Agency",
    "press":       "Press",
    "digital":     "Digital",
    "creative":    "Creative",
    "oo_h":        "OOH",
    "social":      "Social",
    "pr":          "PR",
    "media_buy":   "Media Buy",
}


def normalize_firms(show: dict) -> list[dict]:
    raw = show.get("marketing_firms") or []
    primary_seen = False
    out: list[dict] = []
    for entry in raw:
        firm = (entry.get("firm") or "").strip()
        role = entry.get("role")
        if not firm or role not in VALID_ROLES:
            print(
                f"[build_firms] WARN {show['slug']}: dropping invalid entry "
                f"firm={firm!r} role={role!r}",
                file=sys.stderr,
            )
            continue
        is_primary = bool(entry.get("is_primary"))
        if is_primary and primary_seen:
            print(
                f"[build_firms] WARN {show['slug']}: multiple is_primary firms; "
                f"demoting {firm}",
                file=sys.stderr,
            )
            is_primary = False
        if is_primary:
            primary_seen = True
        out.append({
            "firm": firm,
            "role": role,
            "role_display": ROLE_DISPLAY[role],
            "is_primary": is_primary,
            "is_stub": bool(entry.get("_stub")),
        })
    out.sort(key=lambda f: (not f["is_primary"], f["firm"].lower()))
    return out


def build() -> dict:
    data = json.loads(SHOWS_JSON.read_text())
    by_firm: dict[str, list[dict]] = defaultdict(list)
    enriched_shows: list[dict] = []
    primary_firms: dict[str, dict] = {}

    for show in data["shows"]:
        firms = normalize_firms(show)
        if firms:
            enriched_shows.append({"slug": show["slug"], "firms": firms})
            for f in firms:
                by_firm[f["firm"]].append({
                    "show_slug": show["slug"],
                    "show_title": show["title"],
                    "role": f["role"],
                    "role_display": f["role_display"],
                    "is_primary": f["is_primary"],
                    "weekly_gross_usd": show.get("weekly_gross_usd"),
                })
                if f["is_primary"]:
                    primary_firms[show["slug"]] = {
                        "firm": f["firm"], "role": f["role"],
                    }

    firms_summary = []
    for firm, rows in sorted(by_firm.items()):
        total_gross = sum((r["weekly_gross_usd"] or 0) for r in rows)
        firms_summary.append({
            "firm": firm,
            "show_count": len(rows),
            "primary_count": sum(1 for r in rows if r["is_primary"]),
            "total_weekly_gross_usd": total_gross,
            "shows": sorted(rows, key=lambda r: r["show_title"]),
        })
    firms_summary.sort(key=lambda f: -f["total_weekly_gross_usd"])

    out = {
        "_doc": (
            "Auto-generated by build_firms.py from shows.json marketing_firms[]. "
            "firms[] is sorted by total weekly gross descending. "
            "shows[] lists each show with its firm credits. "
            "Do NOT edit by hand — edit shows.json marketing_firms[] and re-run."
        ),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "firms": firms_summary,
        "shows": enriched_shows,
        "primary_firms_by_show": primary_firms,
    }
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps(out, indent=2))
    return out


def main() -> None:
    data = build()
    print(f"Wrote {OUT_PATH.name}")
    print(f"  firms tracked: {len(data['firms'])}")
    print(f"  shows with credits: {len(data['shows'])}")
    print(f"  primary firms set: {len(data['primary_firms_by_show'])}")


if __name__ == "__main__":
    main()
